### ISSUE TITLE
cmd-F1 does not open Svija Tools

### ISSUE THREAD

**Issue by pwikapanel** [svijasvg/svija-tools-macos#8]
need to leave an alert to say when it's loaded

need to make sure that the correct panel is being called (I changed  the ID)

add alert to calling Script to see if it is running.

**Comment by acswift** [comment]
Have dissected the Adobe CEP example, and made a working copy in **Svija Launcher extension**, but it doesn't pick up the cmd-F1 keystroke if it is not visible, unlike the actual Svija Tools panel.

More investigation is needed but I'm tired today.

**Comment by acswift** [comment]
It is now working.
